# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='images/products/%Y/%m/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='abstractpost',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
