# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0002_auto_20180420_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catecory',
            new_name='Category',
        ),
    ]
