# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0003_auto_20180420_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Featured Image'),
        ),
    ]
