# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0004_auto_20180420_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractCategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_blog.AbstractCategory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_blog.AbstractPost')),
            ],
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='category',
            field=models.ManyToManyField(blank=True, through='web_blog.AbstractCategoryGroup', to='web_blog.AbstractCategory'),
        ),
    ]
