# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0005_auto_20180420_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('abstractcategorygroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_blog.AbstractCategoryGroup')),
            ],
            bases=('web_blog.abstractcategorygroup',),
        ),
        migrations.AlterField(
            model_name='abstractpost',
            name='category',
            field=models.ManyToManyField(blank=True, through='web_blog.AbstractCategoryGroup', to='web_blog.AbstractCategory', verbose_name='Category'),
        ),
    ]
