# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0006_auto_20180420_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcategorygroup',
            name='id',
        ),
        migrations.AddField(
            model_name='abstractcategorygroup',
            name='group',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractcategorygroup',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_blog.Timestamp'),
            preserve_default=False,
        ),
    ]
