# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='abstractpost',
            options={'ordering': ['-post_date', 'title']},
        ),
    ]
