# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0005_auto_20180512_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
