# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_auto_20180512_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='authour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appblog', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
