# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_auto_20180512_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractpost',
            old_name='authour',
            new_name='author',
        ),
    ]
