# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0010_auto_20180512_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
